apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prometheus
  namespace: core-grafana-alloy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: prometheus
    creationPolicy: Owner
  data:
    - secretKey: endpoint
      remoteRef:
        key: services.grafana.prometheus
        property: endpoint

    - secretKey: user
      remoteRef:
        key: services.grafana.prometheus
        property: username

    - secretKey: password
      remoteRef:
        key: services.grafana.prometheus
        property: password
