# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base
  - resources/Certificate--core-longhorn--longhorn.yaml
  - resources/DNSEndpoint--core-longhorn--longhorn.yaml
  - resources/ExternalSecret--core-longhorn--oidc.yaml
  - resources/IngressRoute--core-longhorn--longhorn.yaml
  - resources/Middleware--core-longhorn--oidc.yaml
