apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lets-encrypt
  namespace: core-cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: lets-encrypt
    creationPolicy: Owner
  data:
    - secretKey: tls.key
      remoteRef:
        key: services.letsencrypt.cert
        property: tls.key
