apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare
  namespace: core-cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: cloudflare
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: services.cloudflare.cert-manager
        property: token
