apiVersion: kubesource.rcwz.pl/v1alpha1
kind: Config
sourceDir: _source
targets:
  - directory: app/base
    filter:
      exclude:
        - kind: CustomResourceDefinition
  - directory: crds
    filter:
      include:
        - kind: CustomResourceDefinition
