apiVersion: v1
data:
  config.alloy: |-
    logging {
    	level  = "info"
    	format = "logfmt"
    }

    discovery.kubernetes "pods" {
    	role = "pod"
    }

    discovery.kubernetes "nodes" {
    	role = "node"
    }

    discovery.kubernetes "services" {
    	role = "service"
    }

    discovery.kubernetes "endpoints" {
    	role = "endpoints"
    }

    discovery.kubernetes "endpointslices" {
    	role = "endpointslice"
    }

    discovery.kubernetes "ingresses" {
    	role = "ingress"
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: config
    app.kubernetes.io/instance: alloy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: alloy
    app.kubernetes.io/version: v1.11.2
    helm.sh/chart: alloy-1.3.1
  name: alloy
  namespace: core-grafana-alloy
