apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocket-id
  namespace: core-pocket-id
spec:
  replicas: 1
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      app: pocket-id
  template:
    metadata:
      labels:
        app: pocket-id
    spec:
      containers:
        - name: pocket-id
          image: ghcr.io/pocket-id/pocket-id:v1.13.1-distroless
          env:
            - name: APP_URL
              value: https://pocketid.rcwz.pl
            - name: TRUST_PROXY
              value: "true"
            - name: LOG_LEVEL
              value: debug
            - name: DB_PROVIDER
              value: postgres
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: uri
          ports:
            - containerPort: 1411
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /app/data
          resources:
            requests:
              cpu: "10m"
              memory: "128Mi"
            limits:
              memory: "128Mi"
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      securityContext:
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pocket-id
