apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocket-id
  namespace: core-pocket-id
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
