apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cilium
  namespace: core-cilium
spec:
  template:
    spec:
      initContainers:
        - name: config
          resources:
            requests:
              cpu: 20m
              memory: 128Mi
            limits:
              memory: 128Mi
        - name: apply-sysctl-overwrites
          resources:
            requests:
              cpu: 20m
              memory: 128Mi
            limits:
              memory: 128Mi
        - name: mount-bpf-fs
          resources:
            requests:
              cpu: 20m
              memory: 128Mi
            limits:
              memory: 128Mi
        - name: clean-cilium-state
          resources:
            requests:
              cpu: 20m
              memory: 128Mi
            limits:
              memory: 128Mi
