apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/version: v0.20.2
    helm.sh/chart: external-secrets-0.20.2
  name: external-secrets-webhook
  namespace: core-external-secrets
