apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: talos-etcd-backup-nodes-list
rules:
  - apiGroups:
      - ""
    resources:
      - "nodes"
    verbs:
      - "get"
      - "list"
