apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - Deployment--home-forgejo--forgejo.yaml
  - PersistentVolumeClaim--home-forgejo--gitea-shared-storage.yaml
  - Secret--home-forgejo--forgejo-init.yaml
  - Secret--home-forgejo--forgejo-inline-config.yaml
  - Secret--home-forgejo--forgejo.yaml
  - Service--home-forgejo--forgejo-http.yaml
  - Service--home-forgejo--forgejo-ssh.yaml
