apiVersion: v1
kind: Secret
metadata:
  labels:
    app: forgejo
    app.kubernetes.io/instance: forgejo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: forgejo
    app.kubernetes.io/version: 15.0.3
    helm.sh/chart: forgejo-17.1.1
    version: 15.0.3
  name: forgejo-inline-config
  namespace: home-forgejo
stringData:
  _generals_: "APP_NAME=Forgejo: Beyond coding. We forge.\nRUN_MODE=prod"
  cache: |-
    ADAPTER=memory
    HOST=
  database: DB_TYPE=postgres
  metrics: ENABLED=false
  oauth2_client: |-
    ACCOUNT_LINKING=auto
    ENABLE_AUTO_REGISTRATION=true
    USERNAME=email
  queue: |-
    CONN_STR=
    TYPE=level
  repository: ROOT=/data/git/gitea-repositories
  security: INSTALL_LOCK=true
  server: |-
    APP_DATA_PATH=/data
    DOMAIN=forgejo.rcwz.pl
    ENABLE_PPROF=false
    HTTP_PORT=3000
    PROTOCOL=http
    ROOT_URL=https://forgejo.rcwz.pl/
    SSH_DOMAIN=forgejo-ssh.pigeon-vibe.ts.net
    SSH_LISTEN_PORT=2222
    SSH_PORT=22
    START_SSH_SERVER=true
  service: |-
    ALLOW_ONLY_EXTERNAL_REGISTRATION=true
    DISABLE_REGISTRATION=true
  session: |-
    PROVIDER=db
    PROVIDER_CONFIG=
type: Opaque
