apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: home-media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 300Gi
