configs:
  params:
    server.disable.auth: true
    server.insecure: true

  secret:
    createSecret: false

dex:
  enabled: false

notifications:
  enabled: false

redisSecretInit:
  enabled: false
