apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - CustomResourceDefinition--verticalpodautoscalercheckpoints.autoscaling.k8s.io.yaml
  - CustomResourceDefinition--verticalpodautoscalers.autoscaling.k8s.io.yaml
