apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: core-tailscale
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: services.tailscale.operator
        property: clientId
    - secretKey: client_secret
      remoteRef:
        key: services.tailscale.operator
        property: clientSecret
