apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: tailscale-proxy-resources
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        resources:
          requests:
            cpu: 20m
            memory: 64Mi
          limits:
            memory: 64Mi
      tailscaleInitContainer:
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 32Mi
