apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ClusterRole--kite.yaml
  - ClusterRoleBinding--kite.yaml
  - Deployment--core-kite--kite.yaml
  - Service--core-kite--kite.yaml
  - ServiceAccount--core-kite--kite.yaml
