apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alloy
  namespace: core-grafana-alloy
spec:
  template:
    spec:
      containers:
        - name: alloy
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
