apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepassword-connect
  namespace: core-1password-connect
spec:
  template:
    spec:
      containers:
        - name: connect-api
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
        - name: connect-sync
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
