# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base
  - resources/External-Secret--core-argocd--argocd-redis.yaml
  - resources/External-Secret--core-argocd--argocd-secret.yaml
