apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - CustomResourceDefinition--applications.argoproj.io.yaml
  - CustomResourceDefinition--applicationsets.argoproj.io.yaml
  - CustomResourceDefinition--appprojects.argoproj.io.yaml
