# yaml-language-server: $schema=https://raw.githubusercontent.com/1Password/connect-helm-charts/refs/heads/main/charts/connect/values.schema.json
acceptanceTests:
  enabled: false
  healthCheck:
    enabled: false

connect:
  api:
    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        memory: 64Mi
  sync:
    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        memory: 64Mi
