# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base
  - resources/External-Secret--core-1password-connect--op-credentials.yaml
patches:
  - path: patches/Deployment--core-1password-connect--onepassword-connect.yaml
