apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ingress.k8s.rcwz.pl
    external-dns.alpha.kubernetes.io/ttl: "60"
  labels:
    app.kubernetes.io/instance: traefik-core-traefik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-37.2.0
  name: traefik
  namespace: core-traefik
spec:
  loadBalancerClass: tailscale
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: web
    - name: websecure
      port: 443
      protocol: TCP
      targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik-core-traefik
    app.kubernetes.io/name: traefik
  type: LoadBalancer
