apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-admin
  namespace: home-forgejo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: forgejo-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: addons.forgejo.artuross
        property: username

    - secretKey: password
      remoteRef:
        key: addons.forgejo.artuross
        property: password
