apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-oidc
  namespace: home-forgejo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: forgejo-oidc
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: pocketid.oidc.forgejo
        property: client_id

    - secretKey: secret
      remoteRef:
        key: pocketid.oidc.forgejo
        property: client_secret
