apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: op-credentials
  namespace: core-1password-connect
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: op-credentials
    creationPolicy: Owner
  data:
    - secretKey: 1password-credentials.json
      remoteRef:
        key: addons.1password.credentials
        property: 1password-credentials.json
