# yaml-language-server: $schema=https://raw.githubusercontent.com/vectordotdev/helm-charts/refs/heads/develop/charts/vector/values.yaml
role: "Agent"

service:
  enabled: false

serviceHeadless:
  enabled: false

podHostNetwork: true
