env:
  - name: LOKI_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: loki
        key: endpoint

  - name: LOKI_PASSWORD
    valueFrom:
      secretKeyRef:
        name: loki
        key: password

  - name: LOKI_USER
    valueFrom:
      secretKeyRef:
        name: loki
        key: user

role: "Agent"

service:
  enabled: false

serviceHeadless:
  enabled: false

podHostNetwork: true
