env:
  # Vector 0.57+ disables environment interpolation by default.
  - name: VECTOR_DANGEROUSLY_ALLOW_ENV_VAR_INTERPOLATION
    value: "true"

  - name: LOKI_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: loki
        key: endpoint

  - name: LOKI_PASSWORD
    valueFrom:
      secretKeyRef:
        name: loki
        key: password

  - name: LOKI_USER
    valueFrom:
      secretKeyRef:
        name: loki
        key: user

role: "Agent"

service:
  enabled: false

serviceHeadless:
  enabled: false

podHostNetwork: true

resources:
  requests:
    cpu: 35m
    memory: 256Mi
  limits:
    memory: 256Mi
