# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base
  - resources/Certificate--core-grafana-alloy--alloy.yaml
  - resources/DNSEndpoint--core-grafana-alloy--alloy.yaml
  - resources/ExternalSecret--core-grafana-alloy--prometheus.yaml
  - resources/IngressRoute--core-grafana-alloy--alloy.yaml

patches:
  - path: patches/StatefulSet--core-grafana-alloy--alloy.yaml

configMapGenerator:
  - name: alloy
    namespace: core-grafana-alloy
    files:
      - config.alloy=configs/config.alloy
    behavior: create
    options:
      disableNameSuffixHash: true
