defaultSettings:
  defaultDataPath: /var/mnt/persistent-data
  defaultReplicaCount: "1"

longhornUI:
  replicas: 1

preUpgradeChecker:
  jobEnabled: false

csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1

persistence:
  defaultClassReplicaCount: 1
