apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn
  namespace: core-longhorn
spec:
  secretName: certificate-longhorn

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always

  duration: 720h # 30d
  renewBefore: 240h # 10d

  dnsNames:
    - longhorn.rcwz.pl

  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: lets-encrypt
