apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-namespaces
  namespace: core-argocd
spec:
  project: default
  source:
    repoURL: git@github.com:artuross/homelab
    targetRevision: HEAD
    path: kubernetes/cluster/namespaces
  destination:
    name: in-cluster
    namespace: core-argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: true
