apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: home-media
  namespace: core-argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: git@github.com:artuross/homelab
        revision: HEAD
        directories:
          - path: kubernetes/home/media/*/app
  template:
    metadata:
      name: home-media-{{ index .path.segments 3 }}-app
    spec:
      project: default
      source:
        repoURL: git@github.com:artuross/homelab
        targetRevision: HEAD
        path: "{{ .path.path }}"
      destination:
        name: in-cluster
        namespace: core-argocd
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
          allowEmpty: true
