apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluetun
  namespace: home-media
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
