apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent
  namespace: home-media
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
