apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: home-media
spec:
  type: ClusterIP
  selector:
    app: qbittorrent
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 8080
