apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: core-traefik
spec:
  template:
    spec:
      containers:
        - name: traefik
          securityContext:
            seccompProfile:
              type: RuntimeDefault
