apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: longhorn-csi-bind
  namespace: core-longhorn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: longhorn-csi-role
subjects:
  - kind: ServiceAccount
    name: longhorn-csi-service-account
    namespace: core-longhorn
