apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: cnpg
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/version: 1.27.1
    helm.sh/chart: cloudnative-pg-0.26.1
  name: cnpg-cloudnative-pg-view
rules:
  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - backups
      - clusters
      - clusters/status
      - databases
      - failoverquorums
      - poolers
      - publications
      - scheduledbackups
      - imagecatalogs
      - clusterimagecatalogs
      - subscriptions
    verbs:
      - get
      - list
      - watch
