apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: core-argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: argocd-secret
    creationPolicy: Owner
  data:
    - secretKey: server.secretkey
      remoteRef:
        key: addons.argocd.server
        property: secretKey

    - secretKey: tls.crt
      remoteRef:
        key: addons.argocd.certificates
        property: tls.crt

    - secretKey: tls.key
      remoteRef:
        key: addons.argocd.certificates
        property: tls.key
