apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: core-argocd
spec:
  routes:
    - kind: Rule
      match: Host(`argocd.rcwz.pl`)
      services:
        - kind: Service
          name: argocd-server
          port: 80
