# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: alloy
    namespace: core-grafana-alloy
    repo: https://grafana.github.io/helm-charts
    releaseName: alloy
    includeCRDs: true
    skipHooks: false
    version: 1.3.1
    valuesFile: values.yaml
