apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik
  namespace: core-traefik
spec:
  secretName: certificate-traefik

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always

  duration: 720h # 30d
  renewBefore: 240h # 10d

  dnsNames:
    - traefik.rcwz.pl

  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: lets-encrypt
