# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base
  - resources/ClusterSecretStore--1password.yaml
  - resources/ExternalSecret--core-external-secrets--onepassword-connect-token.yaml
