apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare
  namespace: core-external-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: cloudflare
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: services.cloudflare.external-dns
        property: token
